"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useEffect, useRef, useState } from "react";

import { useAtlasStore } from "@/app/lib/store";
import type { Depth, LearningPath } from "@/app/lib/types";

const OUTLINE_LOADING_MESSAGES = [
  "Designing your learning path…",
  "Picking the best 5 lessons…",
  "Structuring the journey…",
];

const DEPTH_OPTIONS: Array<{
  depth: Depth;
  icon: string;
  title: string;
  tagline: string;
  duration: string;
}> = [
  {
    depth: "quick",
    icon: "⚡",
    title: "Quick Explainer",
    tagline: "Big picture, no jargon",
    duration: "~3 min",
  },
  {
    depth: "solid",
    icon: "🎯",
    title: "Solid Teaching",
    tagline: "Concrete examples and tradeoffs",
    duration: "~15 min",
  },
  {
    depth: "deep",
    icon: "🔬",
    title: "Deep Dive",
    tagline: "Implementation-level detail",
    duration: "~30 min",
  },
];

function AtlasBackground() {
  return (
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(99,102,241,0.18),transparent_32%),radial-gradient(circle_at_bottom_right,rgba(56,189,248,0.12),transparent_28%)]" />
  );
}

function TopBar({ sourceTitle }: { sourceTitle: string }) {
  return (
    <div className="relative border-b border-white/10 bg-zinc-950/70 backdrop-blur">
      <div className="mx-auto flex max-w-6xl flex-col gap-3 px-6 py-4 sm:flex-row sm:items-center sm:justify-between">
        <Link
          className="text-sm uppercase tracking-[0.4em] text-white/55 transition hover:text-white"
          href="/"
        >
          Atlas
        </Link>
        <p className="truncate text-sm text-zinc-300">{sourceTitle}</p>
      </div>
    </div>
  );
}

function CenteredCardShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="rounded-[2rem] border border-white/10 bg-white/5 p-10 shadow-[0_0_0_1px_rgba(255,255,255,0.04),0_32px_120px_rgba(15,23,42,0.45)] backdrop-blur-xl">
      {children}
    </div>
  );
}

function EmptyState() {
  return (
    <main className="relative flex min-h-screen items-center justify-center overflow-hidden px-6 py-24">
      <AtlasBackground />
      <div className="relative w-full max-w-xl">
        <CenteredCardShell>
          <p className="text-sm uppercase tracking-[0.4em] text-white/45">
            Atlas
          </p>
          <h1 className="mt-6 text-3xl font-semibold tracking-[-0.04em] text-white">
            No source loaded.
          </h1>
          <p className="mt-4 text-white/65">
            Start from the homepage to analyze a repository or PDF first.
          </p>
          <Link
            className="mt-8 inline-flex rounded-2xl border border-zinc-700 px-5 py-3 text-sm font-medium text-zinc-100 transition hover:border-zinc-500"
            href="/"
          >
            Start over
          </Link>
        </CenteredCardShell>
      </div>
    </main>
  );
}

function PlanSuspenseFallback() {
  return (
    <main className="relative flex min-h-screen items-center justify-center overflow-hidden px-6 py-24">
      <AtlasBackground />
      <div className="relative w-full max-w-xl">
        <CenteredCardShell>
          <div className="flex items-center justify-center gap-4 text-left">
            <div className="h-5 w-5 animate-spin rounded-full border-2 border-white/20 border-t-indigo-300" />
            <p className="text-base font-medium text-white">Loading plan…</p>
          </div>
        </CenteredCardShell>
      </div>
    </main>
  );
}

function PlanPageContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const ingestionData = useAtlasStore((state) => state.ingestionData);
  const learningPath = useAtlasStore((state) => state.learningPath);
  const depth = useAtlasStore((state) => state.depth);
  const setDepth = useAtlasStore((state) => state.setDepth);
  const setLearningPath = useAtlasStore((state) => state.setLearningPath);
  const invalidateLessons = useAtlasStore((state) => state.invalidateLessons);
  const [phase, setPhase] = useState<"select" | "loading" | "ready" | "error">(
    "select"
  );
  const [outline, setOutline] = useState<LearningPath | null>(null);
  const [selectedDepth, setSelectedDepth] = useState<Depth>(depth);
  const [error, setError] = useState<string | null>(null);
  const [messageIndex, setMessageIndex] = useState(0);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (!ingestionData) {
      return;
    }

    const shouldRegenerate = searchParams.get("regenerate") === "1";

    if (shouldRegenerate && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      setOutline(null);
      setSelectedDepth(depth);
      setError(null);
      setPhase("loading");

      void (async () => {
        try {
          const response = await fetch("/api/outline", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              ingestionData,
              depth,
            }),
          });

          const payload = (await response.json().catch(() => null)) as
            | (LearningPath & { error?: string })
            | null;

          if (!response.ok || !payload) {
            throw new Error(
              typeof payload?.error === "string"
                ? payload.error
                : "Failed to generate outline"
            );
          }

          setOutline(payload);
          setPhase("ready");
          router.replace("/plan");
        } catch (nextError) {
          setError(
            nextError instanceof Error
              ? nextError.message
              : "Failed to generate outline"
          );
          setPhase("error");
        }
      })();

      return;
    }

    if (!shouldRegenerate) {
      hasAutoGeneratedRef.current = false;
    }

    if (learningPath) {
      setOutline(learningPath);
      setSelectedDepth(learningPath.depth);
      setPhase("ready");
      return;
    }

    setOutline(null);
    setSelectedDepth(depth);
    setPhase("select");
  }, [depth, ingestionData, learningPath, router, searchParams]);

  useEffect(() => {
    if (phase !== "loading") {
      setMessageIndex(0);
      return;
    }

    const interval = window.setInterval(() => {
      setMessageIndex((currentIndex) =>
        (currentIndex + 1) % OUTLINE_LOADING_MESSAGES.length
      );
    }, 2000);

    return () => {
      window.clearInterval(interval);
    };
  }, [phase]);

  async function generateOutline(nextDepth: Depth) {
    if (!ingestionData) {
      return;
    }

    setSelectedDepth(nextDepth);
    setDepth(nextDepth);
    setError(null);
    setPhase("loading");

    try {
      const response = await fetch("/api/outline", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          ingestionData,
          depth: nextDepth,
        }),
      });

      const payload = (await response.json().catch(() => null)) as
        | (LearningPath & { error?: string })
        | null;

      if (!response.ok || !payload) {
        throw new Error(
          typeof payload?.error === "string"
            ? payload.error
            : "Failed to generate outline"
        );
      }

      setOutline(payload);
      setPhase("ready");
    } catch (nextError) {
      setError(
        nextError instanceof Error
          ? nextError.message
          : "Failed to generate outline"
      );
      setPhase("error");
    }
  }

  function handleDepthSelection(nextDepth: Depth) {
    setLearningPath(null);
    invalidateLessons();
    void generateOutline(nextDepth);
  }

  function handleStart() {
    if (!outline) {
      return;
    }

    setLearningPath(outline);
    router.push(`/learn/${outline.lessons[0].id}`);
  }

  if (!ingestionData) {
    return <EmptyState />;
  }

  return (
    <main className="relative min-h-screen overflow-hidden">
      <AtlasBackground />
      <TopBar sourceTitle={ingestionData.metadata.fullName} />

      <div className="relative mx-auto max-w-6xl px-6 py-12">
        {phase === "select" ? (
          <div className="mx-auto max-w-5xl">
            <CenteredCardShell>
              <p className="text-sm uppercase tracking-[0.4em] text-white/45">
                Atlas
              </p>
              <h1 className="mt-6 text-4xl font-semibold tracking-[-0.04em] text-white sm:text-5xl">
                How deep do you want to go?
              </h1>
              <p className="mt-4 max-w-2xl text-base leading-7 text-white/65">
                Atlas will tailor the depth of every lesson in your path.
              </p>

              <div className="mt-10 grid gap-4 md:grid-cols-3">
                {DEPTH_OPTIONS.map((option) => (
                  <button
                    className={`rounded-[1.75rem] border p-6 text-left transition ${
                      selectedDepth === option.depth
                        ? "border-indigo-400/40 bg-indigo-500/10 shadow-[0_0_0_1px_rgba(129,140,248,0.16)]"
                        : "border-white/10 bg-zinc-950/45 hover:border-indigo-400/35 hover:bg-indigo-500/5"
                    }`}
                    key={option.depth}
                    onClick={() => {
                      void handleDepthSelection(option.depth);
                    }}
                    type="button"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-2xl" aria-hidden="true">
                        {option.icon}
                      </span>
                      <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs uppercase tracking-[0.25em] text-zinc-400">
                        {option.duration}
                      </span>
                    </div>
                    <h2 className="mt-8 text-2xl font-semibold tracking-[-0.03em] text-white">
                      {option.title}
                    </h2>
                    <p className="mt-3 text-sm leading-6 text-zinc-400">
                      {option.tagline}
                    </p>
                  </button>
                ))}
              </div>
            </CenteredCardShell>
          </div>
        ) : null}

        {phase === "loading" ? (
          <div className="mx-auto max-w-xl">
            <CenteredCardShell>
              <div className="flex items-center justify-center gap-4 text-left">
                <div className="h-5 w-5 animate-spin rounded-full border-2 border-white/20 border-t-indigo-300" />
                <p className="text-base font-medium text-white" aria-live="polite">
                  {OUTLINE_LOADING_MESSAGES[messageIndex]}
                </p>
              </div>
              <p className="mt-4 text-sm text-zinc-400">
                Analyzing your source and picking the right 5 lessons for you.
              </p>
            </CenteredCardShell>
          </div>
        ) : null}

        {phase === "error" ? (
          <div className="mx-auto max-w-xl">
            <CenteredCardShell>
              <h1 className="text-3xl font-semibold tracking-[-0.04em] text-white">
                We couldn&apos;t build your path.
              </h1>
              <p className="mt-4 text-white/65">
                Try again and Atlas will take another pass at structuring the journey.
              </p>
              <p className="mt-3 text-sm text-zinc-500">{error}</p>
              <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
                <button
                  className="inline-flex items-center justify-center rounded-2xl bg-indigo-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-indigo-500"
                  onClick={() => {
                    void generateOutline(selectedDepth);
                  }}
                  type="button"
                >
                  Try again
                </button>
                <button
                  className="inline-flex items-center justify-center rounded-2xl border border-zinc-700 px-5 py-3 text-sm font-medium text-zinc-100 transition hover:border-zinc-500"
                  onClick={() => {
                    setPhase("select");
                    setError(null);
                  }}
                  type="button"
                >
                  Change depth
                </button>
              </div>
            </CenteredCardShell>
          </div>
        ) : null}

        {phase === "ready" && outline ? (
          <div className="mx-auto max-w-4xl">
            <CenteredCardShell>
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="text-sm uppercase tracking-[0.4em] text-white/45">
                    Atlas
                  </p>
                  <h1 className="mt-4 text-4xl font-semibold tracking-[-0.04em] text-white">
                    Your learning path
                  </h1>
                </div>
                <button
                  className="inline-flex items-center rounded-full border border-indigo-400/30 bg-indigo-500/10 px-4 py-2 text-sm font-medium text-indigo-100 transition hover:border-indigo-300/50"
                  onClick={() => {
                    setPhase("select");
                    setOutline(null);
                    setError(null);
                  }}
                  type="button"
                >
                  {outline.depth.charAt(0).toUpperCase() + outline.depth.slice(1)}
                </button>
              </div>

              <div className="mt-10 space-y-4">
                {outline.lessons.map((lesson) => (
                  <div
                    className="rounded-[1.5rem] border border-white/10 bg-zinc-950/45 p-5"
                    key={lesson.id}
                  >
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-start">
                      <p className="min-w-12 text-2xl font-semibold tracking-[-0.04em] text-zinc-600">
                        {lesson.order}
                      </p>
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-3">
                          <h2 className="text-xl font-semibold tracking-[-0.03em] text-white">
                            {lesson.title}
                          </h2>
                          <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs uppercase tracking-[0.22em] text-zinc-400">
                            {lesson.focusArea}
                          </span>
                        </div>
                        <p className="mt-3 text-sm leading-6 text-zinc-400">
                          {lesson.summary}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              <button
                className="mt-10 inline-flex items-center justify-center rounded-2xl bg-indigo-600 px-6 py-3 text-sm font-medium text-white transition hover:bg-indigo-500"
                onClick={handleStart}
                type="button"
              >
                Start Lesson 1 →
              </button>
            </CenteredCardShell>
          </div>
        ) : null}
      </div>
    </main>
  );
}

export default function PlanPage() {
  return (
    <Suspense fallback={<PlanSuspenseFallback />}>
      <PlanPageContent />
    </Suspense>
  );
}
